# Generated by Django 3.0.3 on 2020-12-30 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('popularity', models.FloatField(blank=True, null=True)),
                ('director', models.CharField(db_index=True, max_length=200)),
                ('imdb_score', models.FloatField(blank=True, null=True)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('genre', models.ManyToManyField(to='movies.Genre')),
            ],
        ),
    ]
